apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: station
        image: weather-station:latest